<?php

return [
    'default_plan' => 'menu',
    'fallback_status' => 'pending',
    'blocked_message' => 'هذه الميزة غير متاحة في الباقة الحالية.',

    'statuses' => [
        'active',
        'expired',
        'suspended',
        'cancelled',
        'pending',
    ],

    'grace_features_when_inactive' => [
        'online_menu',
        'qr_menu',
        'offers',
        'popup_campaigns',
    ],

    'features' => [
        'online_menu',
        'qr_menu',
        'cart',
        'checkout',
        'order_tracking',
        'otp',
        'coupons',
        'offers',
        'popup_campaigns',
        'branches',
        'staff_management',
        'kitchen_dashboard',
        'delivery_dashboard',
        'cashier_pos',
        'paymob',
        'reports',
        'audit_logs',
        'theme_switching',
        'ai_assistant',
    ],

    'plans' => [
        'menu' => [
            'label' => 'Menu',
            'features' => [
                'online_menu',
                'qr_menu',
                'offers',
                'popup_campaigns',
            ],
            'limits' => [],
        ],
        'orders' => [
            'label' => 'Orders',
            'features' => [
                'online_menu',
                'qr_menu',
                'cart',
                'checkout',
                'order_tracking',
                'otp',
                'coupons',
                'offers',
                'popup_campaigns',
            ],
            'limits' => [],
        ],
        'operations' => [
            'label' => 'Operations',
            'features' => [
                'online_menu',
                'qr_menu',
                'cart',
                'checkout',
                'order_tracking',
                'otp',
                'coupons',
                'offers',
                'popup_campaigns',
                'branches',
                'staff_management',
                'kitchen_dashboard',
                'delivery_dashboard',
                'cashier_pos',
            ],
            'limits' => [],
        ],
        'pro' => [
            'label' => 'Pro',
            'features' => [
                'online_menu',
                'qr_menu',
                'cart',
                'checkout',
                'order_tracking',
                'otp',
                'coupons',
                'offers',
                'popup_campaigns',
                'branches',
                'staff_management',
                'kitchen_dashboard',
                'delivery_dashboard',
                'cashier_pos',
                'paymob',
                'reports',
                'audit_logs',
                'theme_switching',
                'ai_assistant',
            ],
            'limits' => [],
        ],
    ],
];
